### ISSUE TITLE
Assistance with sending control commands

### ISSUE THREAD

**Issue by dagarzonr** [ThuanLeUte/RMD_X8_PRO_CAN_BUS_CONTROLER#2]
Hi @ThuanLeUte ! 

Thanks for making available this repo. It is an awesome starting point. :)

I just started playing with the X8 Pro and I do not completely understand how the protocol works. If possible, I wished to ask you for a bit of assistance. 

My set up: Adruiono UNO, Sparkfun CAN-BUS Shield , Can wires with 120 Ohm resistor, RMD X 8 PRO.

I tested the motor with the software of MyActuator and works fine there. 

Then, I tried your implementation and I succeed on starting the communications with the motor. When I use the commands RE and RT in the serial terminal of Arduino, they give back reasonable values. However, when I try to command the position or the velocity of the motor, the motor does not move. I am not sure if there is something I should do before sending the velocity (SP) or position (TL) commands. 

The joystic did not work for me too, so I disabled it by commenting [its line in the loop](https://github.com/ThuanLeUte/RMD_X8_PRO_CAN_BUS_CONTROLER/blob/f20dc61d6e7e82429aa97f25273615a069536208/main/main.ino#L117). 

I logged the message that is send to the motor (CAN SEND MSG BUFFER) and the message I receive back (Receiving RMD_X8_POSITION_CTRL_2_CMD) for two angles (TL_90 and TL_180). Could you please take a look? 

```
17:41:42.969 -> TL_90
17:41:42.969 -> 
17:41:42.969 -> TL
17:41:42.969 -> 90
17:41:42.969 -> 
17:41:42.969 -> 90.00
17:41:42.969 -> Set motor run clockwise
17:41:42.969 -> Motor Speed: 10
17:41:42.969 -> CAN SEND MSG BUFFER
17:41:42.969 -> Device ID: 141
17:41:42.969 -> Data 0: A4
17:41:42.969 -> Data 1: 0
17:41:42.969 -> Data 2: 3C
17:41:42.969 -> Data 3: 0
17:41:42.969 -> Data 4: F0
17:41:42.969 -> Data 5: D2
17:41:42.969 -> Data 6: 0
17:41:42.969 -> Data 7: 0
17:41:42.969 -> Can msg receive
17:41:42.969 -> Receiving RMD_X8_POSITION_CTRL_2_CMD
17:41:43.003 -> Data 0: A4
17:41:43.003 -> Data 1: 0
17:41:43.003 -> Data 2: 0
17:41:43.003 -> Data 3: 0
17:41:43.003 -> Data 4: 0
17:41:43.003 -> Data 5: 0
17:41:43.003 -> Data 6: F3
17:41:43.003 -> Data 7: 0

17:42:36.987 -> TL_180
17:42:36.987 -> 
17:42:36.987 -> TL
17:42:36.987 -> 180
17:42:36.987 -> 
17:42:36.987 -> 180.00
17:42:36.987 -> Set motor run clockwise
17:42:36.987 -> Motor Speed: 10
17:42:36.987 -> CAN SEND MSG BUFFER
17:42:36.987 -> Device ID: 141
17:42:36.987 -> Data 0: A4
17:42:36.987 -> Data 1: 0
17:42:37.020 -> Data 2: 3C
17:42:37.020 -> Data 3: 0
17:42:37.020 -> Data 4: E0
17:42:37.020 -> Data 5: A5
17:42:37.020 -> Data 6: 1
17:42:37.020 -> Data 7: 0
17:42:37.020 -> Can msg receive
17:42:37.020 -> Receiving RMD_X8_POSITION_CTRL_2_CMD
17:42:37.020 -> Data 0: A4
17:42:37.020 -> Data 1: 0
17:42:37.020 -> Data 2: 0
17:42:37.020 -> Data 3: 0
17:42:37.020 -> Data 4: 0
17:42:37.020 -> Data 5: 0
17:42:37.020 -> Data 6: F3
17:42:37.020 -> Data 7: 0
```

As far as I understand, the response does not match the one described in the protocol of [MyAactuator](https://91c86f05-550f-4736-a32d-209bd17abad1.filesusr.com/ugd/cab28a_12650a87d0714b5b9df4aa1e4bafca4a.pdf). Am I right? 

I am quite lost with this and any help would be very much appreciated. If it is helpful, I could add a more complete log (just let know what information I should record). 

Thanks again, 

David.

**Comment by ThuanLeUte** [comment]
Hi @dagarzonr ,

I have a look at your question. One note is that, Please make sure your motor and my motor is the same and the documment have to be the same to use my driver.

My motor is : http://www.gyems.cn/866757.html

Please check the documment of your motor and mine

Best regards,
ThuanLe

**Comment by dagarzonr** [comment]
Thanks for replying so quickly. 

I compared the documentation of the RMD X8 Pro of [Gyems](https://www.dropbox.com/s/2yzt90i10d6dn27/RMD%20servo%20motor%20control%20protocol%20%28CAN%20BUS%20%29V1.61.pdf?dl=0) (your motor) and the one of [MyActuator](https://91c86f05-550f-4736-a32d-209bd17abad1.filesusr.com/ugd/cab28a_12650a87d0714b5b9df4aa1e4bafca4a.pdf) (my motor) and they quite similar. The CAN commands they have in common are  the same. 

Today I successfully used your driver. That means that your driver could be extensible to the products of MyActuator too. :)

To make it work, I added a new command that sends  `MOTOR_RUN` using the method [send_command](https://github.com/ThuanLeUte/RMD_X8_PRO_CAN_BUS_CONTROLER/blob/f20dc61d6e7e82429aa97f25273615a069536208/main/x8_can.h#L469). After sending `MOTOR_RUN`, I am able to send the TR and TL commands to control the position of the motor. If I do not execute  `MOTOR_RUN`, the motor does not move. 

I played a bit with TL and TR and I found that they cannot go over 360 deg. That means that TL goes clockwise if the target angle is higher than the current angle; and it will go in the opposite direction if the target angle is lower than the higher angle. Is this the intended behavior of the driver?  Do you know if the continuous rotation can be achieved while using position control?

Also, I noticed that the motor needs a few rotations to set the 0 when it gets a position command (TL or TR) for the first time after turning on. My problem is that the position of 0 changes every time. Have you observed this behavior?

The last question I would have is about using this driver to control 4 motors simultaneously (probably 2 by 2). Do you have any suggestions for doing this?

Thank you so much.

Best,

David

**Comment by ThuanLeUte** [comment]
Hi,

Thank you for your question.

1. The last question I would have is about using this driver to control 4 motors simultaneously (probably 2 by 2). Do you have any suggestions for doing this?
- You can able to control the 4 motors by one MCU. Just need to set the address for the motors.

2. Also, I noticed that the motor needs a few rotations to set the 0 when it gets a position command (TL or TR) for the first time after turning on. My problem is that the position of 0 changes every time. Have you observed this behavior?
-  I have not do that in this driver

3. I played a bit with TL and TR and I found that they cannot go over 360 deg. That means that TL goes clockwise if the target angle is higher than the current angle; and it will go in the opposite direction if the target angle is lower than the higher angle. Is this the intended behavior of the driver? Do you know if the continuous rotation can be achieved while using position control?
- Please check the datasheet: The control value angleControl under this command is limited by the Max Angle value in the host
computer.

Feel free to contact me if you need any supports, I am also available to work on the project as freelancer

Best regards, 
ThuanLe

**Comment by dagarzonr** [comment]
Thank you! I believe I will continue working on it next week. I will close this issue now and open a more specific one if something comes up.

Best, 

David
